version: '3.8'

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'your_user'
      MYSQL_PASSWORD: 'your_password'
      MYSQL_ROOT_PASSWORD: 'your_root_password'
    volumes:
      - mysql_data:/var/lib/mysql # Persist database data
  
volumes:
  mysql_data: